### ISSUE TITLE
Abort trying to set digital output

### ISSUE THREAD

**Issue by JetForMe** [jethornton/7i76e#4]
Hi JT. I tried to build a configuration by setting `Outputs TB6/Output 7` to `Digital Out 3`, and when I clicked `Build Configuration` the program aborted with this output:

```
$ 7i76e
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "/home/rmann/.local/lib/python3.5/site-packages/m7i76e/7i76e.py", line 111, in on_actionBuild_triggered
    result = self.buildio(self)
  File "/home/rmann/.local/lib/python3.5/site-packages/m7i76e/buildfiles.py", line 946, in buildio
    ioContents.append('net digital-out-3 motion.digital-out-03 => hm2_7i76e.0.7i76.0.0.output-0:02}\n'.format(index))
ValueError: Single '}' encountered in format string
Aborted
```

**Comment by jethornton** [comment]
Thanks for letting me know about that typo.

JT
