### ISSUE TITLE
MesaFlash not found on Debian 10 

### ISSUE THREAD

**Issue by factory42designs** [jethornton/7i76e#8]
When running on debian 10 software will start fine but crashes when reading card with error:

7i76e
Traceback (most recent call last):
  File "/home/prcdslnc13/.local/lib/python3.7/site-packages/m7i76e/m7i76e.py", line 189, in cardRead
    card.readCard(self)
  File "/home/prcdslnc13/.local/lib/python3.7/site-packages/m7i76e/card.py", line 7, in readCard
    stderr=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mesaflash64': 'mesaflash64'
Aborted

**Comment by jethornton** [comment]
This has been fixed.
